[package]
edition = "2018"

name = "mbackup"
version = "0.1.0"
authors = [ "Jakob Truelsen <jakob@scalgo.com>" ]

[[bin]]
name = "mbackupd"
path = "src/server/main.rs"

[[bin]]
name = "mbackup"
path = "src/client/main.rs"

[dependencies]
log = ""
simple_logger = ""
rusqlite = ""
rust-crypto = ""
hyper = ""
futures = ""
tokio = ""
rand = ""
reqwest = ""
hex = ""
clap = ""
toml = ""
serde = ""
native-tls = ""
tokio-tls = ""
chrono = ""
base64 = ""
pbr = ""
nix = ""
libc = ""
rust-lzma = ""
itertools = ""
